### ISSUE TITLE
waitThreadFinished proc may hang 

### ISSUE THREAD

**Issue by VitalyKravtsov2016** [mjpcger/JavaPOS-SPF#1]
It is not a good idea to swallow exceptions.
If th == null or if current thread interrupted, this method will hang. 
waitThreadFinished is not needed, only th.join();

    private void waitThreadFinished(Thread th) {
        while (true) {
            try {
                th.join();
                break;
            } catch (Exception e) {}
        }
    }

**Comment by mjpcger** [comment]
I don't believe this is a problem.
waitThreadFinished is private, therefore th cannot be null (in all cases where waitThreadFinished is used, a null pointer exception will be thrown if th is null before waitThreadFinished usage.
The idea is the waitThreadFinished shall retry waiting for the tread termination after the current thread continues after any possible interruption. Since InterruptedException is the only exception thrown by join (if th is not null), this processing seems to be correct for me.
However, I'll change Exception to InterruptedException in next release.
